spring.application.name=swarmbuild

spring.datasource.url=jdbc:postgresql://localhost:5432/swarmbuild
spring.datasource.username=gabrielgouvea
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

swarmbuild.heartbeat.timeout-seconds=60
swarmbuild.bateria.alerta-percentual=20
